services:
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: task-manager
      POSTGRES_PASSWORD: task-manager
    volumes:
      - ./postgres-data:/var/lib/postgresql
  web:
    build:
      context: .
      dockerfile: ./dockerfile
      network: host
    env_file: ./server.env
    ports:
      - "3002:3000"
    restart: always